//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace convenience_store_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public int ID { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public int CashierID { get; set; }
        public int SublistID { get; set; }
        public float Total { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ProductList ProductList { get; set; }
        public virtual User User { get; set; }
    }
}
