//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace convenience_store_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public long ID_Receipt { get; set; }
        public string PaymentDate { get; set; }
        public long CashierID { get; set; }
        public long ProductListID { get; set; }
        public float Total { get; set; }
        public bool Valid { get; set; }
    
        public virtual ProductList ProdList { get; set; }
        public virtual User _User { get; set; }
    }
}
