//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace convenience_store_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int ID { get; set; }
        public int ProductID { get; set; }
        public int Quantity { get; set; }
        public string UnitOfMeasurement { get; set; }
        public System.DateTime SupplyDate { get; set; }
        public float BasePrice { get; set; }
        public float SellingPrice { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
