//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace convenience_store_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public long ID_Stock { get; set; }
        public long Product_ID { get; set; }
        public Nullable<long> Quantity { get; set; }
        public string MeasurementUnit { get; set; }
        public string SupplyDate { get; set; }
        public float AcquisitionPrice { get; set; }
        public float SellingPrice { get; set; }
        public bool Valid { get; set; }
    
        public virtual Product _Product { get; set; }
    }
}
